### ISSUE TITLE
fail2ban_sender twice in README

### ISSUE THREAD

**Issue by mikeshultz** [nbigot/ansible-fail2ban#1]
`fail2ban_sender` is listed twice in README.  Probably want that to be `fail2ban_destemail`.

**Comment by nbigot** [comment]
Hi Mike, thank you for the feed back,
I changed the readme to be more explicit.
Indeed the variable fail2ban_sendername can be either email address or free text because it's for display only wheras the fail2ban_sender variable represents a real email address.

Exemple:
fail2ban_sendername="Mike Shultz"
fail2ban_sender="notifications@github.com"
gives
Mike Shultz <notifications@github.com>

As you noticed the fail2ban_destemail variable was missing in the README so I added it.
Thank you.
